<?php
/**
 * Created by PhpStorm.
 * User: ramiro
 * Date: 18/11/16
 * Time: 10:50 AM
 */

namespace Controllers;


use Models\Connection;
use Models\LaboratoryModel;

class LaboratoryController extends BaseController {
    /** @param Connection $connection */
    public function __construct(Connection $connection) {
        parent::__construct(new LaboratoryModel($connection));
    }

    /**
     * @deprecated
     * @param string $lastSyncDate
     * @return CustomArray
     *
     */
    public function getUpdates($lastSyncDate)
    {
        return parent::getUpdates($lastSyncDate); // TODO: Change the autogenerated stub
    }
}