<?php
/**
 * Created by PhpStorm.
 * User: ramiro
 * Date: 18/11/16
 * Time: 10:50 AM
 */

namespace SIGRI_HC\Controllers;


use SIGRI_HC\Helpers\CustomArray;
use SIGRI_HC\Models\Connection;
use SIGRI_HC\Models\MedicineModel;

class MedicineController extends BaseController {
    /** @param Connection $connection */
    public function __construct(Connection $connection) {
        parent::__construct(new MedicineModel($connection));
    }

    public function get(\DateTime $lastSyncDate = null, $client = null) {
        switch ($client) {
            case DEMANDA:
            case VISITA:
            case HISTORIA:
                $asterisk = true;
                break;
            case AUDITORIA:
                $this->model->setColumns(new CustomArray(["ID_MEDICAMENTO", "DESCRIPCION" => ["DESCRIPCION", "CONCENTRACION", "PRESENTACION"]]));
                $asterisk = false;
                break;
            default:
                $asterisk = true;
        }
        return parent::get($lastSyncDate, $asterisk); // TODO: Change the autogenerated stub
    }
}